import keyMirror from 'keymirror';

export default keyMirror({
  RECIEVE_MEMBERS: null,
  RECIEVE_MEMBERS_ERROR: null,
  RECIEVE_BOARD_MEMBERS: null,
  RECIEVE_BOARD_MEMBERS_ERROR: null,
  RECIEVE_EVENTS: null,
  RECIEVE_EVENTS_ERROR: null,
  RECIEVE_EVENT: null,
  RECIEVE_EVENT_ERROR: null,
  UPDATE_MEMBER: null,
  UPDATE__MEMBERS_ERROR: null,
  UPDATE_EVENT: null,
  UPDATE_EVENT_ERROR: null,
  REMOVE_ATTENDEE: null,
  REMOVE_ATTENDEE_ERROR: null,
  ADD_ATTENDEE: null,
  ADD_ATTENDE_ERROR: null,
});
